version: '3.8'

services:
  mariadb:
	build:
		context: ./requirements/mariadb
		dockerfile: Dockerfile
	image: mariadb.inception
	container_name: mariadb
	env_file:
		- .env
	environment:
		MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
		MYSQL_DATABASE: ${MYSQL_DATABASE}
		MYSQL_USER: ${MYSQL_USER}
		MYSQL_PASSWORD: ${MYSQL_PASSWORD}
	volumes:
		- mariadb_data:/var/lib/mysql
	networks:
		- inception_network
	restart: unless-stopped
	expose:
		- "3306"

	#wordpress avec PHP-FPM container
	wordpress:
		build:
			context: ./requirements/wordpress
			dockerfile: Dockerfile
		image: wordpress.inception
		container_name: wordpress
		env_file:
			- .env
		environment:
			- WP_DB_NAME=${WP_DB_NAME}
			- WP_DB_USER=${WP_DB_USER}
			- WP_DB_PASSWORD=${WP_DB_PASSWORD}
			- WP_DB_HOST=${WP_DB_HOST}
			- WP_TITLE=${WP_TITLE}
			- WP_ADMIN_USER=${WP_ADMIN_USER}
			- WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
			- WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
			- WP_USER=${WP_USER}
			- WP_USER_PASSWORD=${WP_USER_PASSWORD}
			- WP_USER_EMAIL=${WP_USER_EMAIL}
			- DOMAIN_NAME=${DOMAIN_NAME}
		volumes:
			- wordpress_data:/var/www/html
		networks:
			- inception_network #network personalise 
		depends_on:
			- mariadb
		restart: unless-stopped
		expose:
			- "9000"

#nginx avec SSL container
	nginx:
		build:
			context: ./requirements/nginx
			dockerfile: Dockerfile
		image: nginx.inception
		container_name: nginx
		env_file:
			- .env
		environment:
			- DOMAIN_NAME=${DOMAIN_NAME}
		ports:
			- "443:443" #port uniquement expose (HTTPS)
		volumes:
			- wordpress_data:/var/www/html
		networks:
			- inception_network
		depends_on:
			- wordpress
		restart: unless-stopped #pour redemaerrer automatiquement

#docker volumes
	volumes:
	mariadb_data:
		driver: local
		driver_opts:
			type: none
			o: bind
			device: ${DATA_PATH}/mariadb #lie au volume ssd


	wordpress_data:
		driver: local
		driver_opts:
			type: none
			o: bind
			device: ${DATA_PATH}/wordpress

	networks:
	inception_network:
		driver: bridge
